// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMurderMysteryMaster = "murder_mystery_master"

// MurderMysteryMaster mapped from table <murder_mystery_master>
type MurderMysteryMaster struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title             string    `gorm:"column:title;not null" json:"title"`
	JanCode           string    `gorm:"column:jan_code" json:"jan_code"`
	AsinCode          string    `gorm:"column:asin_code" json:"asin_code"`
	ReleaseDate       time.Time `gorm:"column:release_date;not null" json:"release_date"`
	OfficialLink      string    `gorm:"column:official_link" json:"official_link"`
	AmazonLink        string    `gorm:"column:amazon_link" json:"amazon_link"`
	Platform          string    `gorm:"column:platform;not null" json:"platform"`
	Language          string    `gorm:"column:language;not null" json:"language"`
	SurugayaLink      string    `gorm:"column:surugaya_link" json:"surugaya_link"`
	SteamLink         string    `gorm:"column:steam_link" json:"steam_link"`
	EpicgamesLink     string    `gorm:"column:epicgames_link" json:"epicgames_link"`
	DlsiteLink        string    `gorm:"column:dlsite_link" json:"dlsite_link"`
	RakutenBooksLink  string    `gorm:"column:rakuten_books_link" json:"rakuten_books_link"`
	BookwalkerLink    string    `gorm:"column:bookwalker_link" json:"bookwalker_link"`
	FanzaGamesLink    string    `gorm:"column:fanza_games_link" json:"fanza_games_link"`
	Price             float64   `gorm:"column:price" json:"price"`
	Discount          float64   `gorm:"column:discount" json:"discount"`
	OriginalPrice     float64   `gorm:"column:original_price" json:"original_price"`
	ImageLink         string    `gorm:"column:image_link" json:"image_link"`
	Description       string    `gorm:"column:description" json:"description"`
	PlayersMin        int32     `gorm:"column:players_min" json:"players_min"`
	PlayersMax        int32     `gorm:"column:players_max" json:"players_max"`
	PlayTime          int32     `gorm:"column:play_time" json:"play_time"`
	RequiresGm        bool      `gorm:"column:requires_gm" json:"requires_gm"`
	OnlineSupported   bool      `gorm:"column:online_supported" json:"online_supported"`
	Genre             string    `gorm:"column:genre" json:"genre"`
	Replayability     string    `gorm:"column:replayability" json:"replayability"`
	AgeRecommendation string    `gorm:"column:age_recommendation" json:"age_recommendation"`
	CreatedAt         time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MurderMysteryMaster's table name
func (*MurderMysteryMaster) TableName() string {
	return TableNameMurderMysteryMaster
}
