options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ビルドステージ
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}',
      '.'
    ]

  # イメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}'
    ]

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME}',
      '--add-cloudsql-instances', '${_DB_HOST}'
    ]

substitutions:
  _REGION: us-west1
  _REPOSITORY: mmf-repository
  _IMAGE: mmf-back
  _TAG: latest
  _SERVICE_NAME: mmf-back
  _DB_HOST: murder-mystery-fans:asia-northeast1:mmf
  _DB_PORT: "5432"
  _DB_USER: postgres
  _DB_NAME: mmf

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}' 